### ISSUE TITLE
The 5x branch of pyyaml is dead and has a cython 3 compatibility issue, pyyaml 6x should be used, see https://github.com/yaml/pyyaml/issues/601

### ISSUE THREAD

**Issue by rfrey-splunk** [splunk/appinspect-cli-action#101]
https://github.com/splunk/appinspect-cli-action/blob/86656092ff163b181d4502a2bd232b1fe90333bd/requirements.txt#L1

**Comment by artemrys** [comment]
Not possible to update right now, `splunk-appinspect` still depends on `pyyaml` 5.x. Once it will be updated, we will try again.
